import * as React from 'react';
import {
  Dialog,
  DialogSurface,
  DialogTitle,
  DialogBody,
  DialogActions,
  DialogContent,
  Button,
  Input,
  Textarea,
  Checkbox,
  Spinner,
  makeStyles,
  shorthands,
  tokens,
} from '@fluentui/react-components';
import { DismissRegular } from '@fluentui/react-icons';
import { useHelp } from '../contexts/HelpContext';
import { useAppContext } from '../contexts/AppContext';
// App state summary — inline stub (original hook deleted during teardown, will be rebuilt)
interface IAppStateSummary {
  user: { displayName: string; email: string; roles: string[] };
  currentModule: string | null;
  currentUrl: string;
  selectedProject: { projectName: string; projectCode: string } | null;
  enabledFlagCount: number;
  totalFlagCount: number;
  browserInfo: { userAgent: string; screenSize: string; timestamp: string };
  appVersion: string;
}
const useAppStateSummary = (): { getStateSummary: () => IAppStateSummary } => ({
  getStateSummary: (): IAppStateSummary => ({
    user: { displayName: 'Unknown', email: 'unknown', roles: [] },
    currentModule: null,
    currentUrl: typeof window !== 'undefined' ? window.location.href : '',
    selectedProject: null,
    enabledFlagCount: 0,
    totalFlagCount: 0,
    browserInfo: {
      userAgent: typeof navigator !== 'undefined' ? navigator.userAgent : '',
      screenSize: typeof window !== 'undefined' ? `${window.innerWidth}x${window.innerHeight}` : '',
      timestamp: new Date().toISOString(),
    },
    appVersion: '0.0.0',
  }),
});
import { useToast } from '../shared/ToastContainer';
import { AuditAction, EntityType } from '@hbc/sp-services';
import { HBC_COLORS } from '../../theme/tokens';
import html2canvas from 'html2canvas';

const useStyles = makeStyles({
  surface: {
    maxWidth: '560px',
    width: '100%',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('4px'),
    marginBottom: '16px',
  },
  fieldLabel: {
    fontSize: '13px',
    fontWeight: '600',
    color: tokens.colorNeutralForeground1,
  },
  requiredStar: {
    color: tokens.colorStatusDangerForeground1,
  },
  responseNote: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
    marginTop: '4px',
  },
  errorText: {
    fontSize: '12px',
    color: tokens.colorStatusDangerForeground1,
  },
});

function buildEmailHtml(
  subject: string,
  description: string,
  state: IAppStateSummary,
  screenshotDataUrl: string | null
): string {
  const stateRows = [
    ['User', `${state.user.displayName} (${state.user.email})`],
    ['Roles', state.user.roles.join(', ') || 'None'],
    ['Current Module', state.currentModule || 'N/A'],
    ['URL', state.currentUrl],
    ['Selected Project', state.selectedProject ? `${state.selectedProject.projectName} (${state.selectedProject.projectCode})` : 'None'],
    ['Feature Flags', `${state.enabledFlagCount} of ${state.totalFlagCount} enabled`],
    ['Browser', state.browserInfo.userAgent],
    ['Screen Size', state.browserInfo.screenSize],
    ['App Version', state.appVersion],
    ['Timestamp', state.browserInfo.timestamp],
  ];

  const tableRows = stateRows
    .map(([label, value]) =>
      `<tr><td style="padding:6px 12px;font-weight:600;white-space:nowrap;border-bottom:1px solid #E5E7EB;">${label}</td><td style="padding:6px 12px;border-bottom:1px solid #E5E7EB;">${value}</td></tr>`
    )
    .join('');

  const screenshotSection = screenshotDataUrl
    ? `<h3 style="color:${HBC_COLORS.navy};margin-top:24px;">Screenshot</h3><img src="${screenshotDataUrl}" style="max-width:100%;border:1px solid #E5E7EB;border-radius:4px;" alt="Application screenshot" />`
    : '';

  return `
    <div style="font-family:Segoe UI,sans-serif;max-width:700px;margin:0 auto;">
      <div style="background-color:${HBC_COLORS.navy};padding:16px 24px;border-radius:8px 8px 0 0;">
        <h1 style="color:${HBC_COLORS.orange};margin:0;font-size:18px;">HBC Project Controls — Support Request</h1>
      </div>
      <div style="padding:24px;border:1px solid #E5E7EB;border-top:none;border-radius:0 0 8px 8px;">
        <h2 style="color:${HBC_COLORS.navy};margin-top:0;">Subject: ${subject}</h2>
        <h3 style="color:${HBC_COLORS.navy};">Description</h3>
        <p style="white-space:pre-wrap;background:#F9FAFB;padding:12px;border-radius:4px;border:1px solid #E5E7EB;">${description}</p>
        <h3 style="color:${HBC_COLORS.navy};">Application State</h3>
        <table style="width:100%;border-collapse:collapse;font-size:13px;">${tableRows}</table>
        ${screenshotSection}
        <p style="color:#9CA3AF;font-size:11px;margin-top:24px;text-align:center;">
          Generated by HBC Project Controls v${state.appVersion} on ${new Date().toLocaleString()}
        </p>
      </div>
    </div>
  `;
}

export const ContactSupportDialog: React.FC = () => {
  const styles = useStyles();
  const { isContactSupportOpen, closeContactSupport, supportConfig } = useHelp();
  const { dataService, currentUser } = useAppContext();
  const { getStateSummary } = useAppStateSummary();
  const { addToast } = useToast();

  const [subject, setSubject] = React.useState('');
  const [description, setDescription] = React.useState('');
  const [includeScreenshot, setIncludeScreenshot] = React.useState(true);
  const [isSending, setIsSending] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  const resetForm = React.useCallback(() => {
    setSubject('');
    setDescription('');
    setIncludeScreenshot(true);
    setError(null);
  }, []);

  const handleClose = React.useCallback(() => {
    if (!isSending) {
      closeContactSupport();
      resetForm();
    }
  }, [isSending, closeContactSupport, resetForm]);

  const handleSend = React.useCallback(async () => {
    if (!subject.trim() || !description.trim()) {
      setError('Subject and description are required.');
      return;
    }
    if (!supportConfig?.supportEmail) {
      setError('Support email is not configured.');
      return;
    }

    setIsSending(true);
    setError(null);

    try {
      let screenshotDataUrl: string | null = null;

      if (includeScreenshot) {
        try {
          const canvas = await html2canvas(document.body, {
            useCORS: true,
            scale: 0.5,
            logging: false,
          });
          screenshotDataUrl = canvas.toDataURL('image/png');
        } catch (screenshotErr) {
          console.warn('Screenshot capture failed, sending without:', screenshotErr);
        }
      }

      const state = getStateSummary();
      const htmlBody = buildEmailHtml(subject.trim(), description.trim(), state, screenshotDataUrl);

      await dataService.sendSupportEmail(
        supportConfig.supportEmail,
        `[HBC Support] ${subject.trim()}`,
        htmlBody,
        currentUser?.email ?? 'unknown'
      );

      dataService.logAudit({
        Action: AuditAction.SupportEmailSent,
        EntityType: EntityType.SupportRequest,
        EntityId: '',
        User: currentUser?.email ?? 'unknown',
        Details: `Subject: ${subject.trim()}`,
      }).catch(() => { /* fire-and-forget */ });

      addToast('Support request sent successfully', 'success');
      closeContactSupport();
      resetForm();
    } catch (err) {
      console.error('Failed to send support email:', err);
      setError('Failed to send support request. Please try again.');
      addToast('Failed to send support request', 'error');
    } finally {
      setIsSending(false);
    }
  }, [subject, description, includeScreenshot, supportConfig, dataService, currentUser, getStateSummary, addToast, closeContactSupport, resetForm]);

  return (
    <Dialog open={isContactSupportOpen} onOpenChange={(_, data) => { if (!data.open) handleClose(); }}>
      <DialogSurface className={styles.surface}>
        <DialogTitle
          action={
            <Button
              appearance="subtle"
              aria-label="Close"
              icon={<DismissRegular />}
              onClick={handleClose}
              disabled={isSending}
            />
          }
        >
          Contact Support
        </DialogTitle>
        <DialogBody>
          <DialogContent>
            <div className={styles.field}>
              <label className={styles.fieldLabel}>
                Subject <span className={styles.requiredStar}>*</span>
              </label>
              <Input
                placeholder="Brief summary of your issue"
                value={subject}
                onChange={(_, data) => setSubject(data.value)}
                disabled={isSending}
              />
            </div>

            <div className={styles.field}>
              <label className={styles.fieldLabel}>
                Description <span className={styles.requiredStar}>*</span>
              </label>
              <Textarea
                placeholder="Please describe the issue in detail..."
                value={description}
                onChange={(_, data) => setDescription(data.value)}
                rows={4}
                resize="vertical"
                disabled={isSending}
              />
            </div>

            <Checkbox
              checked={includeScreenshot}
              onChange={(_, data) => setIncludeScreenshot(!!data.checked)}
              label="Include a screenshot of the current page"
              disabled={isSending}
            />

            {supportConfig?.responseTimeHours && (
              <p className={styles.responseNote}>
                Our team typically responds within {supportConfig.responseTimeHours} hours.
              </p>
            )}

            {error && <p className={styles.errorText}>{error}</p>}
          </DialogContent>
        </DialogBody>
        <DialogActions>
          <Button appearance="secondary" onClick={handleClose} disabled={isSending}>
            Cancel
          </Button>
          <Button
            appearance="primary"
            onClick={handleSend}
            disabled={isSending || !subject.trim() || !description.trim()}
            icon={isSending ? <Spinner size="tiny" /> : undefined}
          >
            {isSending ? 'Sending...' : 'Send'}
          </Button>
        </DialogActions>
      </DialogSurface>
    </Dialog>
  );
};
