// Permission keys used in RBAC
export const PERMISSIONS = {
  // Lead management
  LEAD_CREATE: 'lead:create',
  LEAD_READ: 'lead:read',
  LEAD_EDIT: 'lead:edit',
  LEAD_DELETE: 'lead:delete',

  // Go/No-Go
  GONOGO_SCORE_ORIGINATOR: 'gonogo:score:originator',
  GONOGO_SCORE_COMMITTEE: 'gonogo:score:committee',
  GONOGO_SUBMIT: 'gonogo:submit',
  GONOGO_DECIDE: 'gonogo:decide',
  GONOGO_READ: 'gonogo:read',

  // Preconstruction
  PRECON_READ: 'precon:read',
  PRECON_EDIT: 'precon:edit',

  // Proposal
  PROPOSAL_READ: 'proposal:read',
  PROPOSAL_EDIT: 'proposal:edit',

  // Win/Loss
  WINLOSS_RECORD: 'winloss:record',
  WINLOSS_READ: 'winloss:read',

  // Contract
  CONTRACT_READ: 'contract:read',
  CONTRACT_EDIT: 'contract:edit',
  CONTRACT_VIEW_FINANCIALS: 'contract:view:financials',

  // Turnover
  TURNOVER_READ: 'turnover:read',
  TURNOVER_EDIT: 'turnover:edit',

  // Closeout
  CLOSEOUT_READ: 'closeout:read',
  CLOSEOUT_EDIT: 'closeout:edit',

  // Estimating
  ESTIMATING_READ: 'estimating:read',
  ESTIMATING_EDIT: 'estimating:edit',

  // Admin
  ADMIN_ROLES: 'admin:roles',
  ADMIN_FLAGS: 'admin:flags',
  ADMIN_CONFIG: 'admin:config',
  ADMIN_CONNECTIONS: 'admin:connections',
  ADMIN_PROVISIONING: 'admin:provisioning',

  // Marketing
  MARKETING_EDIT: 'marketing:edit',

  // Site provisioning
  SITE_PROVISION: 'site:provision',

  // Meeting
  MEETING_SCHEDULE: 'meeting:schedule',
  MEETING_READ: 'meeting:read',
} as const;

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Role to permissions mapping
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  'BD Representative': [
    PERMISSIONS.LEAD_CREATE, PERMISSIONS.LEAD_READ, PERMISSIONS.LEAD_EDIT, PERMISSIONS.LEAD_DELETE,
    PERMISSIONS.GONOGO_SCORE_ORIGINATOR, PERMISSIONS.GONOGO_SUBMIT, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_RECORD, PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.ESTIMATING_READ, PERMISSIONS.MEETING_SCHEDULE, PERMISSIONS.MEETING_READ,
    PERMISSIONS.SITE_PROVISION,
  ],
  'Estimating Coordinator': [
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.GONOGO_SCORE_ORIGINATOR, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_EDIT, PERMISSIONS.PRECON_READ,
    PERMISSIONS.PROPOSAL_EDIT, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.ESTIMATING_READ, PERMISSIONS.ESTIMATING_EDIT,
    PERMISSIONS.MEETING_READ,
  ],
  'Accounting Manager': [
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_VIEW_FINANCIALS,
    PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.ESTIMATING_READ, PERMISSIONS.MEETING_READ,
  ],
  'Preconstruction Team': [
    PERMISSIONS.PRECON_EDIT, PERMISSIONS.PRECON_READ,
    PERMISSIONS.PROPOSAL_EDIT, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.ESTIMATING_READ, PERMISSIONS.MEETING_READ,
  ],
  'Operations Team': [
    PERMISSIONS.TURNOVER_EDIT, PERMISSIONS.TURNOVER_READ,
    PERMISSIONS.CLOSEOUT_EDIT, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
  ],
  'Executive Leadership': [
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.GONOGO_SCORE_COMMITTEE, PERMISSIONS.GONOGO_DECIDE, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_VIEW_FINANCIALS,
    PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.ESTIMATING_READ,
    PERMISSIONS.ADMIN_ROLES, PERMISSIONS.ADMIN_FLAGS, PERMISSIONS.ADMIN_CONFIG, PERMISSIONS.ADMIN_CONNECTIONS, PERMISSIONS.ADMIN_PROVISIONING,
    PERMISSIONS.MEETING_SCHEDULE, PERMISSIONS.MEETING_READ,
  ],
  'Legal': [
    PERMISSIONS.LEAD_READ, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_EDIT,
    PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
  ],
  'Risk Management': [
    PERMISSIONS.LEAD_READ, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
  ],
  'Marketing': [
    PERMISSIONS.LEAD_READ, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.MARKETING_EDIT,
    PERMISSIONS.PROPOSAL_EDIT, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
  ],
  'Quality Control': [
    PERMISSIONS.PRECON_READ,
    PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
  ],
  'Safety': [
    PERMISSIONS.PRECON_READ,
    PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
  ],
  'IDS': [
    PERMISSIONS.PRECON_READ,
    PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ, PERMISSIONS.ADMIN_CONFIG,
  ],
};
