// Permission keys used in RBAC
export const PERMISSIONS = {
  // Lead management
  LEAD_CREATE: 'lead:create',
  LEAD_READ: 'lead:read',
  LEAD_EDIT: 'lead:edit',
  LEAD_DELETE: 'lead:delete',

  // Go/No-Go
  GONOGO_SCORE_ORIGINATOR: 'gonogo:score:originator',
  GONOGO_SCORE_COMMITTEE: 'gonogo:score:committee',
  GONOGO_SUBMIT: 'gonogo:submit',
  GONOGO_DECIDE: 'gonogo:decide',
  GONOGO_READ: 'gonogo:read',

  // Preconstruction
  PRECON_READ: 'precon:read',
  PRECON_EDIT: 'precon:edit',

  // Proposal
  PROPOSAL_READ: 'proposal:read',
  PROPOSAL_EDIT: 'proposal:edit',

  // Win/Loss
  WINLOSS_RECORD: 'winloss:record',
  WINLOSS_READ: 'winloss:read',

  // Contract
  CONTRACT_READ: 'contract:read',
  CONTRACT_EDIT: 'contract:edit',
  CONTRACT_VIEW_FINANCIALS: 'contract:view:financials',

  // Turnover
  TURNOVER_READ: 'turnover:read',
  TURNOVER_EDIT: 'turnover:edit',

  // Closeout
  CLOSEOUT_READ: 'closeout:read',
  CLOSEOUT_EDIT: 'closeout:edit',

  // Estimating
  ESTIMATING_READ: 'estimating:read',
  ESTIMATING_EDIT: 'estimating:edit',

  // Module access
  PRECON_HUB_VIEW: 'precon:hub:view',
  PROJECT_HUB_VIEW: 'project:hub:view',

  // Admin
  ADMIN_ROLES: 'admin:roles',
  ADMIN_FLAGS: 'admin:flags',
  ADMIN_CONFIG: 'admin:config',
  ADMIN_CONNECTIONS: 'admin:connections',
  ADMIN_PROVISIONING: 'admin:provisioning',

  // Marketing
  MARKETING_EDIT: 'marketing:edit',
  MARKETING_DASHBOARD_VIEW: 'marketing:dashboard:view',

  // Site provisioning
  SITE_PROVISION: 'site:provision',

  // Meeting
  MEETING_SCHEDULE: 'meeting:schedule',
  MEETING_READ: 'meeting:read',

  // Project Startup
  STARTUP_CHECKLIST_EDIT: 'startup:checklist:edit',
  STARTUP_CHECKLIST_SIGNOFF: 'startup:checklist:signoff',
  MATRIX_EDIT: 'matrix:edit',
  PROJECT_RECORD_EDIT: 'projectrecord:edit',
  PROJECT_RECORD_OPS_EDIT: 'projectrecord:ops:edit',

  // Project Management Plan
  PMP_EDIT: 'pmp:edit',
  PMP_APPROVE: 'pmp:approve',
  PMP_FINAL_APPROVE: 'pmp:final:approve',
  PMP_SIGN: 'pmp:sign',

  // Operational Modules
  RISK_EDIT: 'risk:edit',
  QUALITY_EDIT: 'quality:edit',
  SAFETY_EDIT: 'safety:edit',
  SCHEDULE_EDIT: 'schedule:edit',
  SUPERINTENDENT_PLAN_EDIT: 'superintendent:plan:edit',
  LESSONS_EDIT: 'lessons:edit',

  // Monthly Review
  MONTHLY_REVIEW_PM: 'monthly:review:pm',
  MONTHLY_REVIEW_PX: 'monthly:review:px',
  MONTHLY_REVIEW_CREATE: 'monthly:review:create',

  // Job Number Requests
  JOB_NUMBER_REQUEST_CREATE: 'job_number_request:create',
  JOB_NUMBER_REQUEST_FINALIZE: 'job_number_request:finalize',
  ACCOUNTING_QUEUE_VIEW: 'accounting_queue:view',

  // Estimating Kick-Off
  KICKOFF_VIEW: 'kickoff:view',
  KICKOFF_EDIT: 'kickoff:edit',
  KICKOFF_TEMPLATE_EDIT: 'kickoff:template:edit',

  // Post-Bid Autopsy
  AUTOPSY_VIEW: 'autopsy:view',
  AUTOPSY_EDIT: 'autopsy:edit',
  AUTOPSY_SCHEDULE: 'autopsy:schedule',

  // Buyout Log
  BUYOUT_VIEW: 'buyout:view',
  BUYOUT_EDIT: 'buyout:edit',
  BUYOUT_MANAGE: 'buyout:manage',
} as const;

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Role to permissions mapping
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  'BD Representative': [
    PERMISSIONS.LEAD_CREATE, PERMISSIONS.LEAD_READ, PERMISSIONS.LEAD_EDIT, PERMISSIONS.LEAD_DELETE,
    PERMISSIONS.GONOGO_SCORE_ORIGINATOR, PERMISSIONS.GONOGO_SUBMIT, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_RECORD, PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.ESTIMATING_READ, PERMISSIONS.MEETING_SCHEDULE, PERMISSIONS.MEETING_READ,
    PERMISSIONS.SITE_PROVISION,
    PERMISSIONS.KICKOFF_VIEW,
    PERMISSIONS.AUTOPSY_VIEW,
  ],
  'Estimating Coordinator': [
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.GONOGO_SCORE_ORIGINATOR, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_EDIT, PERMISSIONS.PRECON_READ,
    PERMISSIONS.PROPOSAL_EDIT, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.ESTIMATING_READ, PERMISSIONS.ESTIMATING_EDIT,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.JOB_NUMBER_REQUEST_CREATE,
    PERMISSIONS.KICKOFF_VIEW, PERMISSIONS.KICKOFF_EDIT, PERMISSIONS.KICKOFF_TEMPLATE_EDIT,
    PERMISSIONS.AUTOPSY_VIEW, PERMISSIONS.AUTOPSY_EDIT, PERMISSIONS.AUTOPSY_SCHEDULE,
    PERMISSIONS.PRECON_HUB_VIEW, PERMISSIONS.PROJECT_HUB_VIEW,
  ],
  'Accounting Manager': [
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_VIEW_FINANCIALS,
    PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.ESTIMATING_READ, PERMISSIONS.MEETING_READ,
    PERMISSIONS.JOB_NUMBER_REQUEST_FINALIZE, PERMISSIONS.ACCOUNTING_QUEUE_VIEW,
  ],
  'Preconstruction Team': [
    PERMISSIONS.PRECON_EDIT, PERMISSIONS.PRECON_READ,
    PERMISSIONS.PROPOSAL_EDIT, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.ESTIMATING_READ, PERMISSIONS.MEETING_READ,
    PERMISSIONS.KICKOFF_VIEW,
    PERMISSIONS.AUTOPSY_VIEW,
    PERMISSIONS.BUYOUT_VIEW,
  ],
  'Operations Team': [
    PERMISSIONS.TURNOVER_EDIT, PERMISSIONS.TURNOVER_READ,
    PERMISSIONS.CLOSEOUT_EDIT, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.STARTUP_CHECKLIST_EDIT, PERMISSIONS.MATRIX_EDIT, PERMISSIONS.PROJECT_RECORD_OPS_EDIT,
    PERMISSIONS.PMP_EDIT, PERMISSIONS.PMP_SIGN, PERMISSIONS.MONTHLY_REVIEW_PM,
    PERMISSIONS.RISK_EDIT, PERMISSIONS.QUALITY_EDIT, PERMISSIONS.SAFETY_EDIT,
    PERMISSIONS.SCHEDULE_EDIT, PERMISSIONS.SUPERINTENDENT_PLAN_EDIT, PERMISSIONS.LESSONS_EDIT,
    PERMISSIONS.BUYOUT_VIEW, PERMISSIONS.BUYOUT_EDIT, PERMISSIONS.BUYOUT_MANAGE,
    PERMISSIONS.PROJECT_HUB_VIEW,
  ],
  'Executive Leadership': [
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.GONOGO_SCORE_COMMITTEE, PERMISSIONS.GONOGO_DECIDE, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_VIEW_FINANCIALS,
    PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.ESTIMATING_READ,
    PERMISSIONS.ADMIN_ROLES, PERMISSIONS.ADMIN_FLAGS, PERMISSIONS.ADMIN_CONFIG, PERMISSIONS.ADMIN_CONNECTIONS, PERMISSIONS.ADMIN_PROVISIONING,
    PERMISSIONS.MEETING_SCHEDULE, PERMISSIONS.MEETING_READ,
    PERMISSIONS.STARTUP_CHECKLIST_SIGNOFF, PERMISSIONS.MARKETING_DASHBOARD_VIEW,
    PERMISSIONS.PMP_APPROVE, PERMISSIONS.PMP_FINAL_APPROVE, PERMISSIONS.PMP_SIGN,
    PERMISSIONS.MONTHLY_REVIEW_PX, PERMISSIONS.MONTHLY_REVIEW_CREATE,
    PERMISSIONS.KICKOFF_VIEW, PERMISSIONS.KICKOFF_EDIT, PERMISSIONS.KICKOFF_TEMPLATE_EDIT,
    PERMISSIONS.AUTOPSY_VIEW, PERMISSIONS.AUTOPSY_EDIT, PERMISSIONS.AUTOPSY_SCHEDULE,
    PERMISSIONS.BUYOUT_VIEW, PERMISSIONS.BUYOUT_EDIT,
    PERMISSIONS.PRECON_HUB_VIEW, PERMISSIONS.PROJECT_HUB_VIEW,
  ],
  'Legal': [
    PERMISSIONS.LEAD_READ, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.CONTRACT_EDIT,
    PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
  ],
  'Risk Management': [
    PERMISSIONS.LEAD_READ, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.RISK_EDIT,
  ],
  'Marketing': [
    PERMISSIONS.LEAD_READ, PERMISSIONS.GONOGO_READ,
    PERMISSIONS.PRECON_READ, PERMISSIONS.MARKETING_EDIT,
    PERMISSIONS.PROPOSAL_EDIT, PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.PROJECT_RECORD_EDIT, PERMISSIONS.MARKETING_DASHBOARD_VIEW,
  ],
  'Quality Control': [
    PERMISSIONS.PRECON_READ,
    PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.QUALITY_EDIT,
  ],
  'Safety': [
    PERMISSIONS.PRECON_READ,
    PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ,
  ],
  'IDS': [
    PERMISSIONS.PRECON_READ,
    PERMISSIONS.PROPOSAL_READ,
    PERMISSIONS.WINLOSS_READ,
    PERMISSIONS.CONTRACT_READ, PERMISSIONS.TURNOVER_READ, PERMISSIONS.CLOSEOUT_READ,
    PERMISSIONS.MEETING_READ, PERMISSIONS.ADMIN_CONFIG,
  ],
};
